[package]
name = "minesweeper_ctg"
version = "0.1.3"
edition = "2024"
authors = ["arnaudelrio", "<arnau.delrio@gmail.com>"]
description = "A CLI/TUI/GUI minesweeper program"
readme = "README.md"
license = "GPL-3.0-or-later"
repository = "https://github.com/arnaudelrio/minesweeper"
keywords = ["minesweeper", "tui", "cli", "gui"]

[features]
default = ["mine_gui"]
cli = []
mine_tui = ["crossterm", "tui"]
mine_gui = ["yew", "wasm-bindgen", "getrandom"]

[dependencies]
crossterm = { version = "0.29.0", optional = true }
getrandom = { version = "0.3.4", features = ["wasm_js"], optional = true }
rand = "0.9.2"
tui = { version = "0.19.0", optional = true }
wasm-bindgen = { version = "0.2.106", optional = true, default-features = false }
web-sys = "0.3.83"
yew = { version = "0.22.0", features = ["csr"], optional = true }
